{-
   DaDaPush Public API
   DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

   The version of the OpenAPI document: v1
   Contact: contacts@dadapush.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.MessagePushRequest exposing (MessagePushRequest, decoder, encode)

import Data.Action as Action exposing (Action)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias MessagePushRequest =
    { actions : Maybe ((List Action))
    , content : String
    , needPush : Bool
    , title : String
    }


decoder : Decoder MessagePushRequest
decoder =
    Decode.succeed MessagePushRequest
        |> optional "actions" (Decode.nullable (Decode.list Action.decoder)) Nothing
        |> required "content" Decode.string
        |> required "needPush" Decode.bool
        |> required "title" Decode.string



encode : MessagePushRequest -> Encode.Value
encode model =
    Encode.object
        [ ( "actions", Maybe.withDefault Encode.null (Maybe.map (Encode.list Action.encode) model.actions) )
        , ( "content", Encode.string model.content )
        , ( "needPush", Encode.bool model.needPush )
        , ( "title", Encode.string model.title )

        ]


