{-
   DaDaPush Public API
   DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

   The version of the OpenAPI document: v1
   Contact: contacts@dadapush.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.MessageObject exposing (MessageObject, decoder, encode)

import Data.Action as Action exposing (Action)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias MessageObject =
    { actions : Maybe ((List Action))
    , channelName : String
    , content : String
    , createdAt : String
    , id : Int
    , title : String
    }


decoder : Decoder MessageObject
decoder =
    Decode.succeed MessageObject
        |> optional "actions" (Decode.nullable (Decode.list Action.decoder)) Nothing
        |> required "channelName" Decode.string
        |> required "content" Decode.string
        |> required "createdAt" Decode.string
        |> required "id" Decode.int
        |> required "title" Decode.string



encode : MessageObject -> Encode.Value
encode model =
    Encode.object
        [ ( "actions", Maybe.withDefault Encode.null (Maybe.map (Encode.list Action.encode) model.actions) )
        , ( "channelName", Encode.string model.channelName )
        , ( "content", Encode.string model.content )
        , ( "createdAt", Encode.string model.createdAt )
        , ( "id", Encode.int model.id )
        , ( "title", Encode.string model.title )

        ]


