{-
   DaDaPush Public API
   DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

   The version of the OpenAPI document: v1
   Contact: contacts@dadapush.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.PageResponseOfMessageObject exposing (PageResponseOfMessageObject, decoder, encode)

import Data.MessageObject as MessageObject exposing (MessageObject)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias PageResponseOfMessageObject =
    { content : Maybe ((List MessageObject))
    , totalElements : Maybe (Int)
    , totalPages : Maybe (Int)
    }


decoder : Decoder PageResponseOfMessageObject
decoder =
    Decode.succeed PageResponseOfMessageObject
        |> optional "content" (Decode.nullable (Decode.list MessageObject.decoder)) Nothing
        |> optional "totalElements" (Decode.nullable Decode.int) Nothing
        |> optional "totalPages" (Decode.nullable Decode.int) Nothing



encode : PageResponseOfMessageObject -> Encode.Value
encode model =
    Encode.object
        [ ( "content", Maybe.withDefault Encode.null (Maybe.map (Encode.list MessageObject.encode) model.content) )
        , ( "totalElements", Maybe.withDefault Encode.null (Maybe.map Encode.int model.totalElements) )
        , ( "totalPages", Maybe.withDefault Encode.null (Maybe.map Encode.int model.totalPages) )

        ]


