{-
   DaDaPush Public API
   DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.

   The version of the OpenAPI document: v1
   Contact: contacts@dadapush.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Data.ResultOfPageResponseOfMessageObject exposing (ResultOfPageResponseOfMessageObject, decoder, encode)

import Data.PageResponseOfMessageObject as PageResponseOfMessageObject exposing (PageResponseOfMessageObject)
import Dict exposing (Dict)
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (optional, required)
import Json.Encode as Encode


type alias ResultOfPageResponseOfMessageObject =
    { code : Int
    , data : Maybe (PageResponseOfMessageObject)
    , errmsg : String
    }


decoder : Decoder ResultOfPageResponseOfMessageObject
decoder =
    Decode.succeed ResultOfPageResponseOfMessageObject
        |> required "code" Decode.int
        |> optional "data" (Decode.nullable PageResponseOfMessageObject.decoder) Nothing
        |> required "errmsg" Decode.string



encode : ResultOfPageResponseOfMessageObject -> Encode.Value
encode model =
    Encode.object
        [ ( "code", Encode.int model.code )
        , ( "data", Maybe.withDefault Encode.null (Maybe.map PageResponseOfMessageObject.encode model.data) )
        , ( "errmsg", Encode.string model.errmsg )

        ]


